# Generated by Django 5.1 on 2024-09-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('supermercado', 'Supermercado'), ('restaurante', 'Restaurante'), ('hotel', 'Hotel')], max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('billetera', models.CharField(blank=True, max_length=42, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('billetera', models.CharField(blank=True, max_length=42, null=True)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_empaque', models.DateTimeField(auto_now_add=True)),
                ('peso_pallet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
                ('tipo_caja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_pallet', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('lugar', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('billetera', models.CharField(blank=True, max_length=42, null=True)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('auto', models.CharField(blank=True, max_length=100, null=True)),
                ('patente', models.CharField(blank=True, max_length=7, null=True)),
                ('rut', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('billetera', models.CharField(blank=True, max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_caja', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('peso_caja', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.cliente')),
                ('empaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.empaque')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('ruta_inicio_latitude', models.FloatField(blank=True, null=True)),
                ('ruta_inicio_longitude', models.FloatField(blank=True, null=True)),
                ('ruta_final_latitude', models.FloatField(blank=True, null=True)),
                ('ruta_final_longitude', models.FloatField(blank=True, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('peso_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.pallet')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.transporte')),
            ],
        ),
        migrations.AddField(
            model_name='pallet',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.predio'),
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('estado_recepcion', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('en_proceso', 'En Proceso'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.distribuidor')),
                ('envio_pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.enviopallet')),
            ],
        ),
        migrations.AddField(
            model_name='empaque',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.recepcion'),
        ),
        migrations.CreateModel(
            name='EnvioCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('ruta_inicio_latitude', models.FloatField(blank=True, null=True)),
                ('ruta_inicio_longitude', models.FloatField(blank=True, null=True)),
                ('ruta_final_latitude', models.FloatField(blank=True, null=True)),
                ('ruta_final_longitude', models.FloatField(blank=True, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.caja')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.transporte')),
            ],
        ),
    ]
