# Generated by Django 5.1 on 2024-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=42, unique=True)),
                ('area', models.CharField(choices=[('cosecha', 'Cosecha'), ('transporte', 'Transporte')], max_length=20)),
            ],
        ),
    ]
