# Generated by Django 5.1 on 2024-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('fecha_cosecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('cantidad_lote', models.IntegerField()),
                ('cantidad_agua', models.IntegerField()),
                ('pesticidas_fertilizantes', models.TextField()),
                ('practicas_cultivo', models.TextField()),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='codigo_qr/')),
                ('transportado', models.BooleanField(default=False)),
            ],
        ),
    ]
