# Generated by Django 5.1 on 2024-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empaque',
            name='tipo_caja',
        ),
        migrations.AddField(
            model_name='caja',
            name='tipo_caja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
