# Generated by Django 5.1 on 2024-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0002_remove_empaque_tipo_caja_caja_tipo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_caja',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
