# Generated by Django 5.1 on 2024-09-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0003_rename_codigo_qr_cosecha_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
