# Generated by Django 5.1 on 2024-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0004_pago_enviocaja_pallet_distribuidor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviocaja',
            name='estado_envio',
        ),
        migrations.AddField(
            model_name='caja',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=100),
        ),
    ]
