# Generated by Django 5.1 on 2024-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0005_remove_enviocaja_estado_envio_caja_estado_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviopallet',
            name='peso_final',
        ),
        migrations.AddField(
            model_name='recepcion',
            name='peso_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
