# Generated by Django 5.1 on 2024-10-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0006_remove_enviopallet_peso_final_recepcion_peso_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviopallet',
            name='coordenadastransporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
