# Generated by Django 5.1 on 2024-10-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0008_remove_enviopallet_coordenadastransporte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepcion',
            old_name='peso_final',
            new_name='peso_recepcion',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='empaque',
        ),
        migrations.AddField(
            model_name='caja',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.recepcion'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='cantidad_cajas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
