# Generated by Django 5.1 on 2024-10-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0009_rename_peso_final_recepcion_peso_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='peso_ingresado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('en_ruta', 'En Ruta')], default='pendiente', max_length=50),
        ),
        migrations.CreateModel(
            name='DistribuidorPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_enviado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_pallet', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=50)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.distribuidor')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.pallet')),
            ],
        ),
    ]
