# Generated by Django 5.1 on 2024-10-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0011_remove_pallet_distribuidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=20)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recicable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.tipocaja'),
        ),
    ]
