# Generated by Django 5.1 on 2024-10-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0012_tipocaja_alter_caja_tipo_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='peso_caja',
        ),
    ]
