# Generated by Django 5.1 on 2024-10-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0013_remove_caja_peso_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
