# Generated by Django 5.1 on 2024-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0014_alter_cliente_rut_alter_predio_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='producto',
            field=models.CharField(choices=[('tomate', 'Tomate'), ('zanahoria', 'Zanahoria'), ('lechuga', 'Lechuga'), ('brócoli', 'Brócoli')], max_length=100),
        ),
    ]
