# Generated by Django 5.1 on 2024-10-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0015_alter_pallet_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='clasificacion',
            field=models.CharField(choices=[('Hortaliza de Hoja', 'Hortaliza de Hoja'), ('Hortaliza de Fruto', 'Hortaliza de Fruto'), ('Hortaliza de Raíz', 'Hortaliza de Raíz'), ('Hortaliza de Flor', 'Hortaliza de Flor')], max_length=100),
        ),
    ]
