# Generated by Django 5.1 on 2024-10-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0016_alter_pallet_clasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='enviocaja',
        ),
        migrations.CreateModel(
            name='RecepcionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_registrado', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.caja')),
            ],
        ),
        migrations.DeleteModel(
            name='Empaque',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
