# Generated by Django 5.1 on 2024-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0017_remove_pago_cliente_remove_pago_enviocaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado')], default='pendiente', max_length=100),
        ),
    ]
