# Generated by Django 5.1 on 2024-10-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0018_alter_caja_estado_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, choices=[('HYUNDAI', 'Hyundai'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('FOTON', 'Foton'), ('CHEVROLET', 'Chevrolet'), ('IVECO', 'Iveco'), ('HINO', 'Hino')], max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('emision_co2', models.DecimalField(decimal_places=2, help_text='Emisión de CO₂ en g/km', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='patente',
        ),
        migrations.AddField(
            model_name='transporte',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.vehiculo'),
        ),
    ]
