# Generated by Django 5.1 on 2024-10-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0019_vehiculo_remove_transporte_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='enviopallet',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.vehiculo'),
        ),
    ]
