# Generated by Django 5.1 on 2024-10-25 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0020_remove_transporte_vehiculo_enviopallet_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocaja',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SIA.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La patente debe tener el formato AAAA00.', regex='^[A-Z]{4}\\d{2}$')]),
        ),
    ]
