# Generated by Django 5.1 on 2024-10-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0021_enviocaja_vehiculo_alter_vehiculo_patente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='emision_co2',
        ),
    ]
