# Generated by Django 5.1 on 2024-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0022_remove_vehiculo_emision_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocaja',
            name='coordenadas_transporte',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
