# Generated by Django 5.1 on 2024-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0023_enviocaja_coordenadas_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
