# Generated by Django 5.1 on 2024-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0024_alter_cliente_rut_alter_distribuidor_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('HYUNDAI', 'Hyundai'), ('MERCEDES_BENZ', 'Mercedes-Benz'), ('FOTON', 'Foton'), ('CHEVROLET', 'Chevrolet'), ('IVECO', 'Iveco'), ('HINO', 'Hino')], default='Hyundai', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
